function escapeCell(value) {
  return String(value ?? "-").replaceAll("|", "\\|");
}

function certificationScore(result) {
  if (!result.manifest) return { met: 0, total: 8 };
  const manifest = result.manifest;
  const criteria = [
    Boolean(manifest.lifecycle),
    Boolean(manifest.support),
    (manifest.canonicalFor ?? []).every(Boolean),
    result.contractFindings.every((finding) => finding.declared),
    result.sourceFindings.every((finding) => finding.excepted),
    result.checks.filter((check) => check.id.startsWith("command:")).every((check) => check.passed),
    manifest.noKey?.status === "certified" || manifest.noKey?.status === "not-applicable",
    Boolean(manifest.proof?.receiptSchema),
  ];
  return { met: criteria.filter(Boolean).length, total: criteria.length };
}

export function renderDashboard(results, registry) {
  const lines = [
    "# Node Platform Ecosystem Status",
    "",
    "> Generated by `nodekit dashboard`. Lifecycle and ownership come from the central registry; command declarations and drift are checked from each repository's `nodekit.yaml` and source tree.",
    "",
    "| Repository | Lifecycle | Role | Commands | No-key | Proof schema | Contract drift | P0 contract |",
    "|---|---|---|---:|---:|---:|---:|---:|",
  ];

  for (const result of results) {
    const name = result.manifest ? result.manifest.repository.split("/").at(-1) : result.name;
    const catalog = registry.repositoryCatalog.repositories.find((repo) => repo.name === name);
    const score = certificationScore(result);
    const commandChecks = result.checks.filter((check) => check.id.startsWith("command:"));
    const setup = commandChecks.length > 0 && commandChecks.every((check) => check.passed) ? "PASS" : "FAIL";
    const drift = result.contractFindings.filter((finding) => !finding.declared).length +
      result.sourceFindings.filter((finding) => !finding.excepted).length;
    lines.push(
      `| ${escapeCell(name)} | ${escapeCell(catalog?.lifecycle)} | ${escapeCell(catalog?.role)} | ${setup} | ${escapeCell(result.manifest?.noKey?.status)} | ${result.manifest?.proof?.receiptSchema ? "DECLARED" : "MISSING"} | ${drift} | ${score.met}/${score.total} |`,
    );
  }

  const migrationConcepts = Object.entries(registry.ownership.concepts).filter(([, concept]) =>
    ["migration-planned", "planned"].includes(concept.status),
  );
  lines.push("", "## Planned Extractions", "");
  for (const [id, concept] of migrationConcepts) {
    const source = concept.currentSource
      ? `; current source: \`${concept.currentSource.repository}/${concept.currentSource.path}\``
      : "";
    lines.push(`- \`${id}\` -> \`${concept.targetPackage ?? "not assigned"}\`${source}`);
  }

  lines.push(
    "",
    "A PASS here means the P0 repository contract is internally consistent. Commands are declared and statically resolvable; this table does not claim they were executed by the dashboard. It does not promote a preview repository to production or turn a planned package into a released package.",
    "",
  );
  return lines.join("\n");
}
